/*
 * Harbour 3.2.0dev (r2312082217)
 * GNU C 13.2 (64-bit)
 * Generated C source from "source/sqlrdd.hbx"
 */

#include "hbvmpub.h"
#include "hbinit.h"


HB_FUNC_EXTERN( AADDDISTINCT );
HB_FUNC_EXTERN( AADDRANGE );
HB_FUNC_EXTERN( AADDRANGEDISTINCT );
HB_FUNC_EXTERN( ADDTOMLHASH );
HB_FUNC_EXTERN( ADISTINCT );
HB_FUNC_EXTERN( ALGEBRASET );
HB_FUNC_EXTERN( AREPLACENILBY );
HB_FUNC_EXTERN( ARITHMETICOPERATOR );
HB_FUNC_EXTERN( AWHERE );
HB_FUNC_EXTERN( BOOLEANEXPRESSION );
HB_FUNC_EXTERN( CJOIN );
HB_FUNC_EXTERN( CLIPPEREXPRESSION );
HB_FUNC_EXTERN( COLLECTALIASES );
HB_FUNC_EXTERN( COMPARISON );
HB_FUNC_EXTERN( COMPARISONOPERATOR );
HB_FUNC_EXTERN( COMPOSEDCONDITION );
HB_FUNC_EXTERN( COMPOSEDCONDITIONBASE );
HB_FUNC_EXTERN( COMPOSEDEXPRESSION );
HB_FUNC_EXTERN( CONDITIONBASE );
HB_FUNC_EXTERN( CONDITIONPARSER );
HB_FUNC_EXTERN( CONDITIONSIMPLIFIER );
HB_FUNC_EXTERN( CONVERTTOCONDITION );
HB_FUNC_EXTERN( CPATTERN );
HB_FUNC_EXTERN( DBCOUNT );
HB_FUNC_EXTERN( DBFIELD );
HB_FUNC_EXTERN( DBINDEX );
HB_FUNC_EXTERN( DETECTDBFROMDSN );
HB_FUNC_EXTERN( DICTIONARY );
HB_FUNC_EXTERN( DIRECTRELATION );
HB_FUNC_EXTERN( ENCHANCEDDIRECTRELATION );
HB_FUNC_EXTERN( ENCHANCEDRELATIONFACTORY );
HB_FUNC_EXTERN( EXPRESSION );
HB_FUNC_EXTERN( EXPRESSIONBASE );
HB_FUNC_EXTERN( EXPRESSIONPARSER );
HB_FUNC_EXTERN( EXPRESSIONSIMPLIFIER );
HB_FUNC_EXTERN( EXPRESSIONSIMPLIFIERBASE );
HB_FUNC_EXTERN( EXPRESSIONTRANSLATOR );
HB_FUNC_EXTERN( EXTENDWORKAREA );
HB_FUNC_EXTERN( FBBEGINTRANSACTION );
HB_FUNC_EXTERN( FBCLOSE );
HB_FUNC_EXTERN( FBCOMMITTRANSACTION );
HB_FUNC_EXTERN( FBCONNECT );
HB_FUNC_EXTERN( FBCREATEDB );
HB_FUNC_EXTERN( FBDESCRIBECOL );
HB_FUNC_EXTERN( FBERROR );
HB_FUNC_EXTERN( FBEXECUTE );
HB_FUNC_EXTERN( FBEXECUTEIMMEDIATE );
HB_FUNC_EXTERN( FBFETCH );
HB_FUNC_EXTERN( FBGETDATA );
HB_FUNC_EXTERN( FBLINEPROCESSED );
HB_FUNC_EXTERN( FBNUMRESULTCOLS );
HB_FUNC_EXTERN( FBROLLBACKTRANSACTION );
HB_FUNC_EXTERN( FBVERSION );
HB_FUNC_EXTERN( FUNCTIONEXPRESSION );
HB_FUNC_EXTERN( GETCONTROLLINGINDEX );
HB_FUNC_EXTERN( GETFIELDBYNAME );
HB_FUNC_EXTERN( GETFIELDS );
HB_FUNC_EXTERN( GETFILENAME );
HB_FUNC_EXTERN( GETINDEXES );
HB_FUNC_EXTERN( GETJOINTSFIELDS );
HB_FUNC_EXTERN( GETMLHASH );
HB_FUNC_EXTERN( INDIRECTRELATION );
HB_FUNC_EXTERN( ISERIALCOMPOSITION );
HB_FUNC_EXTERN( ISSQLWORKAREA );
HB_FUNC_EXTERN( ITEMCMP );
HB_FUNC_EXTERN( KEYVALUEPAIR );
HB_FUNC_EXTERN( LOGICALOPERATOR );
HB_FUNC_EXTERN( MSSQLEXPRESSIONTRANSLATOR );
HB_FUNC_EXTERN( MYSAFFECTEDROWS );
HB_FUNC_EXTERN( MYSCLEAR );
HB_FUNC_EXTERN( MYSCOLS );
HB_FUNC_EXTERN( MYSCOMMIT );
HB_FUNC_EXTERN( MYSCONNECT );
HB_FUNC_EXTERN( MYSERRMSG );
HB_FUNC_EXTERN( MYSEXEC );
HB_FUNC_EXTERN( MYSFETCH );
HB_FUNC_EXTERN( MYSFINISH );
HB_FUNC_EXTERN( MYSGETCONNID );
HB_FUNC_EXTERN( MYSKILLCONNID );
HB_FUNC_EXTERN( MYSLINEPROCESSED );
HB_FUNC_EXTERN( MYSQUERYATTR );
HB_FUNC_EXTERN( MYSRESSTATUS );
HB_FUNC_EXTERN( MYSRESULTSTATUS );
HB_FUNC_EXTERN( MYSROLLBACK );
HB_FUNC_EXTERN( MYSSTATUS );
HB_FUNC_EXTERN( MYSTABLEATTR );
HB_FUNC_EXTERN( MYSVERS );
HB_FUNC_EXTERN( NEWDBCLEARFILTER );
HB_FUNC_EXTERN( NEWDBCLEARRELATION );
HB_FUNC_EXTERN( NEWDBSETRELATION );
HB_FUNC_EXTERN( NEWPARSEFORCLAUSE );
HB_FUNC_EXTERN( OGETWORKAREA );
HB_FUNC_EXTERN( OPERATOR );
HB_FUNC_EXTERN( PARAMETER );
HB_FUNC_EXTERN( PARSERBASE );
HB_FUNC_EXTERN( PGSAFFECTEDROWS );
HB_FUNC_EXTERN( PGSCLEAR );
HB_FUNC_EXTERN( PGSCOLS );
HB_FUNC_EXTERN( PGSCOMMIT );
HB_FUNC_EXTERN( PGSCONNECT );
HB_FUNC_EXTERN( PGSERRMSG );
HB_FUNC_EXTERN( PGSEXEC );
HB_FUNC_EXTERN( PGSFETCH );
HB_FUNC_EXTERN( PGSFINISH );
HB_FUNC_EXTERN( PGSGETDATA );
HB_FUNC_EXTERN( PGSLINEPROCESSED );
HB_FUNC_EXTERN( PGSQUERYATTR );
HB_FUNC_EXTERN( PGSRESSTATUS );
HB_FUNC_EXTERN( PGSRESULTSTATUS );
HB_FUNC_EXTERN( PGSROLLBACK );
HB_FUNC_EXTERN( PGSSTATUS );
HB_FUNC_EXTERN( PGSSTATUS2 );
HB_FUNC_EXTERN( PGSTABLEATTR );
HB_FUNC_EXTERN( RELATIONBASE );
HB_FUNC_EXTERN( RELATIONFACTORY );
HB_FUNC_EXTERN( RELATIONMANAGER );
HB_FUNC_EXTERN( REMOVEALL );
HB_FUNC_EXTERN( SELECTFIRSTAREANOTINUSE );
HB_FUNC_EXTERN( SERIALOPERATOR );
HB_FUNC_EXTERN( SETFIREBIRDUSESHORTASNUM );
HB_FUNC_EXTERN( SETPGSOLDBEHAVIOR );
HB_FUNC_EXTERN( SPLITCONDITION );
HB_FUNC_EXTERN( SQLBINDBYVAL );
HB_FUNC_EXTERN( SQLEX );
HB_FUNC_EXTERN( SQLEX_GETFUNCTABLE );
HB_FUNC_EXTERN( SQLFASTHASH );
HB_FUNC_EXTERN( SQLRDD );
HB_FUNC_EXTERN( SQLRDD_GETFUNCTABLE );
HB_FUNC_EXTERN( SR_ADDCONNECTION );
HB_FUNC_EXTERN( SR_ADDRULENOTNULL );
HB_FUNC_EXTERN( SR_ADDTOFILTER );
HB_FUNC_EXTERN( SR_ADJUSTNUM );
HB_FUNC_EXTERN( SR_ALLINCACHE );
HB_FUNC_EXTERN( SR_ALLOCCO );
HB_FUNC_EXTERN( SR_ALLOCEN );
HB_FUNC_EXTERN( SR_ALLOCST );
HB_FUNC_EXTERN( SR_ARRAYTOXML );
HB_FUNC_EXTERN( SR_AUTOCOMMIT );
HB_FUNC_EXTERN( SR_BEGINTRANSACTION );
HB_FUNC_EXTERN( SR_BLANKVAR );
HB_FUNC_EXTERN( SR_CDBVALUE );
HB_FUNC_EXTERN( SR_CHANGESTRUCT );
HB_FUNC_EXTERN( SR_CHECKCNN );
HB_FUNC_EXTERN( SR_CHECKCONNECTION );
HB_FUNC_EXTERN( SR_CHECKMGMNTIND );
HB_FUNC_EXTERN( SR_CLEANTABINFOCACHE );
HB_FUNC_EXTERN( SR_CLEARFILTER );
HB_FUNC_EXTERN( SR_COLATTRIBUTE );
HB_FUNC_EXTERN( SR_COMMIT );
HB_FUNC_EXTERN( SR_COMMITTRANSACTION );
HB_FUNC_EXTERN( SR_CONNECTION );
HB_FUNC_EXTERN( SR_CREATECONSTRAINT );
HB_FUNC_EXTERN( SR_DBQUALIFY );
HB_FUNC_EXTERN( SR_DBREFRESH );
HB_FUNC_EXTERN( SR_DBSTRUCT );
HB_FUNC_EXTERN( SR_DELETEDNAME );
HB_FUNC_EXTERN( SR_DESCRIB );
HB_FUNC_EXTERN( SR_DESERIALIZE );
HB_FUNC_EXTERN( SR_DESERIALIZE1 );
HB_FUNC_EXTERN( SR_DETECTDBFROMDSN );
HB_FUNC_EXTERN( SR_DISABLEHISTORIC );
HB_FUNC_EXTERN( SR_DISCONN );
HB_FUNC_EXTERN( SR_DRIVERC );
HB_FUNC_EXTERN( SR_DROPCONSTRAINT );
HB_FUNC_EXTERN( SR_DROPINDEX );
HB_FUNC_EXTERN( SR_DROPRULENOTNULL );
HB_FUNC_EXTERN( SR_DROPTABLE );
HB_FUNC_EXTERN( SR_DTODOT );
HB_FUNC_EXTERN( SR_DTOSDOT );
HB_FUNC_EXTERN( SR_DTOUS );
HB_FUNC_EXTERN( SR_ENABLEHISTORIC );
HB_FUNC_EXTERN( SR_END );
HB_FUNC_EXTERN( SR_ENDCONNECTION );
HB_FUNC_EXTERN( SR_ENDTRANSACTION );
HB_FUNC_EXTERN( SR_ERROR );
HB_FUNC_EXTERN( SR_ERRORONGOTOTOINVALIDRECORD );
HB_FUNC_EXTERN( SR_ESCAPENUM );
HB_FUNC_EXTERN( SR_ESCAPESTRING );
HB_FUNC_EXTERN( SR_EVALFILTERS );
HB_FUNC_EXTERN( SR_EXECDIR );
HB_FUNC_EXTERN( SR_EXISTINDEX );
HB_FUNC_EXTERN( SR_EXISTTABLE );
HB_FUNC_EXTERN( SR_FETCH );
HB_FUNC_EXTERN( SR_FETCHSIZE );
HB_FUNC_EXTERN( SR_FILE );
HB_FUNC_EXTERN( SR_FILTERSTATUS );
HB_FUNC_EXTERN( SR_FIREBIRD );
HB_FUNC_EXTERN( SR_FIXCACHEPOINTER );
HB_FUNC_EXTERN( SR_FREECON );
HB_FUNC_EXTERN( SR_FREEENV );
HB_FUNC_EXTERN( SR_FREESTM );
HB_FUNC_EXTERN( SR_FROMXML );
HB_FUNC_EXTERN( SR_GETACTIVECONNECTION );
HB_FUNC_EXTERN( SR_GETACTIVEDT );
HB_FUNC_EXTERN( SR_GETCNN );
HB_FUNC_EXTERN( SR_GETCONNECTION );
HB_FUNC_EXTERN( SR_GETCONNECTIONINFO );
HB_FUNC_EXTERN( SR_GETCONNECTOPTION );
HB_FUNC_EXTERN( SR_GETCURRINSTANCEID );
HB_FUNC_EXTERN( SR_GETERRMESSAGEMAX );
HB_FUNC_EXTERN( SR_GETFASTOPEN );
HB_FUNC_EXTERN( SR_GETGLOBALOWNER );
HB_FUNC_EXTERN( SR_GETINDEXINFOBLOCK );
HB_FUNC_EXTERN( SR_GETINFO );
HB_FUNC_EXTERN( SR_GETINTERNALID );
HB_FUNC_EXTERN( SR_GETNCONNECTION );
HB_FUNC_EXTERN( SR_GETNEXTRECORDBLOCK );
HB_FUNC_EXTERN( SR_GETORACLESYNTHETICVIRTUAL );
HB_FUNC_EXTERN( SR_GETRDDNAME );
HB_FUNC_EXTERN( SR_GETSQL2008NEWTYPES );
HB_FUNC_EXTERN( SR_GETSTACK );
HB_FUNC_EXTERN( SR_GETSVINDEX );
HB_FUNC_EXTERN( SR_GETSYNTHETICINDEX );
HB_FUNC_EXTERN( SR_GETSYNTHETICINDEXMINIMUN );
HB_FUNC_EXTERN( SR_GETTABLEINFOBLOCK );
HB_FUNC_EXTERN( SR_GETTOOLSOWNER );
HB_FUNC_EXTERN( SR_GETUNIQUESYSTEMID );
HB_FUNC_EXTERN( SR_GETUSEJSON );
HB_FUNC_EXTERN( SR_GETUSEXMLFIELD );
HB_FUNC_EXTERN( SR_GOPHANTOM );
HB_FUNC_EXTERN( SR_HASFILTERS );
HB_FUNC_EXTERN( SR_HASHISTORIC );
HB_FUNC_EXTERN( SR_HEXTOSTR );
HB_FUNC_EXTERN( SR_HISTEXPRESSION );
HB_FUNC_EXTERN( SR_HISTEXPRESSIONWHERE );
HB_FUNC_EXTERN( SR_INDEXATTR );
HB_FUNC_EXTERN( SR_INIT );
HB_FUNC_EXTERN( SR_ISWAHIST );
HB_FUNC_EXTERN( SR_LASTSQLERROR );
HB_FUNC_EXTERN( SR_LISTCREATEDTABLES );
HB_FUNC_EXTERN( SR_LISTINDEX );
HB_FUNC_EXTERN( SR_LISTLOCKS );
HB_FUNC_EXTERN( SR_LISTTABLES );
HB_FUNC_EXTERN( SR_LOGFILE );
HB_FUNC_EXTERN( SR_MAXROWCACHE );
HB_FUNC_EXTERN( SR_MORERESULTS );
HB_FUNC_EXTERN( SR_MSG );
HB_FUNC_EXTERN( SR_MSGLOGFILE );
HB_FUNC_EXTERN( SR_MYSQL );
HB_FUNC_EXTERN( SR_NUMRES );
HB_FUNC_EXTERN( SR_ODBC );
HB_FUNC_EXTERN( SR_ODBCGETLINES );
HB_FUNC_EXTERN( SR_ODBCLINEPROCESSED );
HB_FUNC_EXTERN( SR_ODBCWRITEMEMO );
HB_FUNC_EXTERN( SR_ORDCONDSET );
HB_FUNC_EXTERN( SR_PARSEFILENAME );
HB_FUNC_EXTERN( SR_PARSERVERSION );
HB_FUNC_EXTERN( SR_PCODEDESCR );
HB_FUNC_EXTERN( SR_PGS );
HB_FUNC_EXTERN( SR_PHFILE );
HB_FUNC_EXTERN( SR_QUICKAPPEND );
HB_FUNC_EXTERN( SR_RECNONAME );
HB_FUNC_EXTERN( SR_RELEASELOCKS );
HB_FUNC_EXTERN( SR_RELOADFIELDMODIFIERS );
HB_FUNC_EXTERN( SR_RELOADMLHASH );
HB_FUNC_EXTERN( SR_RENAMETABLE );
HB_FUNC_EXTERN( SR_RESETSTATISTICS );
HB_FUNC_EXTERN( SR_ROLLBACK );
HB_FUNC_EXTERN( SR_ROLLBACKTRANSACTION );
HB_FUNC_EXTERN( SR_RUNTIMEERR );
HB_FUNC_EXTERN( SR_SERIALIZE1 );
HB_FUNC_EXTERN( SR_SETACTIVECONNECTION );
HB_FUNC_EXTERN( SR_SETACTIVEDATE );
HB_FUNC_EXTERN( SR_SETACTIVEDT );
HB_FUNC_EXTERN( SR_SETALLOWRELATIONSININDX );
HB_FUNC_EXTERN( SR_SETALOCKWAIT );
HB_FUNC_EXTERN( SR_SETAPPSITE );
HB_FUNC_EXTERN( SR_SETAPPUSER );
HB_FUNC_EXTERN( SR_SETBASELANG );
HB_FUNC_EXTERN( SR_SETBUFFERPOOLSIZE );
HB_FUNC_EXTERN( SR_SETCOLLATION );
HB_FUNC_EXTERN( SR_SETCOLPK );
HB_FUNC_EXTERN( SR_SETCONNECTATTR );
HB_FUNC_EXTERN( SR_SETCONNECTIONLOGCHANGES );
HB_FUNC_EXTERN( SR_SETCONNECTOPTION );
HB_FUNC_EXTERN( SR_SETCREATEASHISTORIC );
HB_FUNC_EXTERN( SR_SETCURRDATE );
HB_FUNC_EXTERN( SR_SETEXCLUSIVEMANAGEMENT );
HB_FUNC_EXTERN( SR_SETFASTOPEN );
HB_FUNC_EXTERN( SR_SETFIELDDEFAULT );
HB_FUNC_EXTERN( SR_SETFILTER );
HB_FUNC_EXTERN( SR_SETFOUND );
HB_FUNC_EXTERN( SR_SETGLOBALOWNER );
HB_FUNC_EXTERN( SR_SETGOTOPONSCOPE );
HB_FUNC_EXTERN( SR_SETHIDEHISTORIC );
HB_FUNC_EXTERN( SR_SETHIDERECNO );
HB_FUNC_EXTERN( SR_SETINDEXINFOBLOCK );
HB_FUNC_EXTERN( SR_SETJOIN );
HB_FUNC_EXTERN( SR_SETLGOTOPONFIRSTINTERACT );
HB_FUNC_EXTERN( SR_SETLOCKS );
HB_FUNC_EXTERN( SR_SETLUSEDBCATALOGS );
HB_FUNC_EXTERN( SR_SETMININUMVARCHAR2SIZE );
HB_FUNC_EXTERN( SR_SETMULTILANG );
HB_FUNC_EXTERN( SR_SETMYSQLMEMODATATYPE );
HB_FUNC_EXTERN( SR_SETMYSQLNUMERICDATATYPE );
HB_FUNC_EXTERN( SR_SETNEXTDT );
HB_FUNC_EXTERN( SR_SETNEXTQUERY );
HB_FUNC_EXTERN( SR_SETNEXTRECORDBLOCK );
HB_FUNC_EXTERN( SR_SETNEXTSVVERS );
HB_FUNC_EXTERN( SR_SETNLINECOUNTRESULT );
HB_FUNC_EXTERN( SR_SETNWGCOMPAT );
HB_FUNC_EXTERN( SR_SETORACLESYNTHETICVIRTUAL );
HB_FUNC_EXTERN( SR_SETPAGEREADSIZE );
HB_FUNC_EXTERN( SR_SETRDDTEMP );
HB_FUNC_EXTERN( SR_SETREVERSEINDEX );
HB_FUNC_EXTERN( SR_SETROOTLANG );
HB_FUNC_EXTERN( SR_SETSECONDLANG );
HB_FUNC_EXTERN( SR_SETSERIALIZEARRAYASJSON );
HB_FUNC_EXTERN( SR_SETSERIALIZEDSTRING );
HB_FUNC_EXTERN( SR_SETSHUTDOWN );
HB_FUNC_EXTERN( SR_SETSQL2008NEWTYPES );
HB_FUNC_EXTERN( SR_SETSTMTOPTION );
HB_FUNC_EXTERN( SR_SETSVINDEX );
HB_FUNC_EXTERN( SR_SETSYNTHETICINDEX );
HB_FUNC_EXTERN( SR_SETSYNTHETICINDEXMINIMUN );
HB_FUNC_EXTERN( SR_SETTABLEINFOBLOCK );
HB_FUNC_EXTERN( SR_SETTBLMGMNT );
HB_FUNC_EXTERN( SR_SETTBLSPACEDATA );
HB_FUNC_EXTERN( SR_SETTBLSPACEINDX );
HB_FUNC_EXTERN( SR_SETTBLSPACELOB );
HB_FUNC_EXTERN( SR_SETTIMETRACE );
HB_FUNC_EXTERN( SR_SETTOOLSOWNER );
HB_FUNC_EXTERN( SR_SETTRACELOG );
HB_FUNC_EXTERN( SR_SETUSEDTHISTAUTO );
HB_FUNC_EXTERN( SR_SETUSEJSON );
HB_FUNC_EXTERN( SR_SETUSESEQUENCES );
HB_FUNC_EXTERN( SR_SETUSEXMLFIELD );
HB_FUNC_EXTERN( SR_SHOWVECTOR );
HB_FUNC_EXTERN( SR_SQLCODEGEN );
HB_FUNC_EXTERN( SR_SQLPARSE );
HB_FUNC_EXTERN( SR_SQLQUOTEDSTRING );
HB_FUNC_EXTERN( SR_STARTLOG );
HB_FUNC_EXTERN( SR_STARTTRACE );
HB_FUNC_EXTERN( SR_STOPLOG );
HB_FUNC_EXTERN( SR_STOPTRACE );
HB_FUNC_EXTERN( SR_STRTOHEX );
HB_FUNC_EXTERN( SR_TABLEATTR );
HB_FUNC_EXTERN( SR_TABLES );
HB_FUNC_EXTERN( SR_TBLMGMNT );
HB_FUNC_EXTERN( SR_TCNEXTRECORD );
HB_FUNC_EXTERN( SR_TRANSACTIONCOUNT );
HB_FUNC_EXTERN( SR_UCHARTOVAL );
HB_FUNC_EXTERN( SR_USEDELETEDS );
HB_FUNC_EXTERN( SR_USENULLSFIRST );
HB_FUNC_EXTERN( SR_USESEQUENCES );
HB_FUNC_EXTERN( SR_VAL2CHAR );
HB_FUNC_EXTERN( SR_VAL2CHARQ );
HB_FUNC_EXTERN( SR_VERSION );
HB_FUNC_EXTERN( SR_WORKAREA );
HB_FUNC_EXTERN( SR_WORKAREAFILENAME );
HB_FUNC_EXTERN( SR_WRITEDBLOG );
HB_FUNC_EXTERN( SR_WRITETIMELOG );
HB_FUNC_EXTERN( TODICTIONARY );
HB_FUNC_EXTERN( TRANSLATIONRESULT );
HB_FUNC_EXTERN( VALUEEXPRESSION );
HB_FUNC_EXTERN( VISUALIZE );
HB_FUNC_EXTERN( XFIRST );
HB_FUNC_EXTERN( XFIRSTORDEFAULT );
HB_FUNC_EXTERN( XSELECT );
HB_FUNC_EXTERN( XSELECTMANY );
HB_FUNC_EXTERN( _SR_REGISTER );
HB_FUNC_EXTERN( _SR_SCANEXEC );
HB_FUNC_EXTERN( _SR_SCANEXECALL );
HB_FUNC_EXTERN( _SR_UNREGISTER );
HB_FUNC_EXTERN( __SR_STARTSQL );
HB_FUNC( __HBEXTERN__SQLRDD__ );


HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_SQLRDD )
{ "AADDDISTINCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADDDISTINCT )}, NULL },
{ "AADDRANGE", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADDRANGE )}, NULL },
{ "AADDRANGEDISTINCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( AADDRANGEDISTINCT )}, NULL },
{ "ADDTOMLHASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( ADDTOMLHASH )}, NULL },
{ "ADISTINCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( ADISTINCT )}, NULL },
{ "ALGEBRASET", {HB_FS_PUBLIC}, {HB_FUNCNAME( ALGEBRASET )}, NULL },
{ "AREPLACENILBY", {HB_FS_PUBLIC}, {HB_FUNCNAME( AREPLACENILBY )}, NULL },
{ "ARITHMETICOPERATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( ARITHMETICOPERATOR )}, NULL },
{ "AWHERE", {HB_FS_PUBLIC}, {HB_FUNCNAME( AWHERE )}, NULL },
{ "BOOLEANEXPRESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( BOOLEANEXPRESSION )}, NULL },
{ "CJOIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( CJOIN )}, NULL },
{ "CLIPPEREXPRESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( CLIPPEREXPRESSION )}, NULL },
{ "COLLECTALIASES", {HB_FS_PUBLIC}, {HB_FUNCNAME( COLLECTALIASES )}, NULL },
{ "COMPARISON", {HB_FS_PUBLIC}, {HB_FUNCNAME( COMPARISON )}, NULL },
{ "COMPARISONOPERATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( COMPARISONOPERATOR )}, NULL },
{ "COMPOSEDCONDITION", {HB_FS_PUBLIC}, {HB_FUNCNAME( COMPOSEDCONDITION )}, NULL },
{ "COMPOSEDCONDITIONBASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( COMPOSEDCONDITIONBASE )}, NULL },
{ "COMPOSEDEXPRESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( COMPOSEDEXPRESSION )}, NULL },
{ "CONDITIONBASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( CONDITIONBASE )}, NULL },
{ "CONDITIONPARSER", {HB_FS_PUBLIC}, {HB_FUNCNAME( CONDITIONPARSER )}, NULL },
{ "CONDITIONSIMPLIFIER", {HB_FS_PUBLIC}, {HB_FUNCNAME( CONDITIONSIMPLIFIER )}, NULL },
{ "CONVERTTOCONDITION", {HB_FS_PUBLIC}, {HB_FUNCNAME( CONVERTTOCONDITION )}, NULL },
{ "CPATTERN", {HB_FS_PUBLIC}, {HB_FUNCNAME( CPATTERN )}, NULL },
{ "DBCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBCOUNT )}, NULL },
{ "DBFIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBFIELD )}, NULL },
{ "DBINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( DBINDEX )}, NULL },
{ "DETECTDBFROMDSN", {HB_FS_PUBLIC}, {HB_FUNCNAME( DETECTDBFROMDSN )}, NULL },
{ "DICTIONARY", {HB_FS_PUBLIC}, {HB_FUNCNAME( DICTIONARY )}, NULL },
{ "DIRECTRELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( DIRECTRELATION )}, NULL },
{ "ENCHANCEDDIRECTRELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( ENCHANCEDDIRECTRELATION )}, NULL },
{ "ENCHANCEDRELATIONFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( ENCHANCEDRELATIONFACTORY )}, NULL },
{ "EXPRESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPRESSION )}, NULL },
{ "EXPRESSIONBASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPRESSIONBASE )}, NULL },
{ "EXPRESSIONPARSER", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPRESSIONPARSER )}, NULL },
{ "EXPRESSIONSIMPLIFIER", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPRESSIONSIMPLIFIER )}, NULL },
{ "EXPRESSIONSIMPLIFIERBASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPRESSIONSIMPLIFIERBASE )}, NULL },
{ "EXPRESSIONTRANSLATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXPRESSIONTRANSLATOR )}, NULL },
{ "EXTENDWORKAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( EXTENDWORKAREA )}, NULL },
{ "FBBEGINTRANSACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBBEGINTRANSACTION )}, NULL },
{ "FBCLOSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBCLOSE )}, NULL },
{ "FBCOMMITTRANSACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBCOMMITTRANSACTION )}, NULL },
{ "FBCONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBCONNECT )}, NULL },
{ "FBCREATEDB", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBCREATEDB )}, NULL },
{ "FBDESCRIBECOL", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBDESCRIBECOL )}, NULL },
{ "FBERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBERROR )}, NULL },
{ "FBEXECUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBEXECUTE )}, NULL },
{ "FBEXECUTEIMMEDIATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBEXECUTEIMMEDIATE )}, NULL },
{ "FBFETCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBFETCH )}, NULL },
{ "FBGETDATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBGETDATA )}, NULL },
{ "FBLINEPROCESSED", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBLINEPROCESSED )}, NULL },
{ "FBNUMRESULTCOLS", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBNUMRESULTCOLS )}, NULL },
{ "FBROLLBACKTRANSACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBROLLBACKTRANSACTION )}, NULL },
{ "FBVERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( FBVERSION )}, NULL },
{ "FUNCTIONEXPRESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( FUNCTIONEXPRESSION )}, NULL },
{ "GETCONTROLLINGINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETCONTROLLINGINDEX )}, NULL },
{ "GETFIELDBYNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETFIELDBYNAME )}, NULL },
{ "GETFIELDS", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETFIELDS )}, NULL },
{ "GETFILENAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETFILENAME )}, NULL },
{ "GETINDEXES", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETINDEXES )}, NULL },
{ "GETJOINTSFIELDS", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETJOINTSFIELDS )}, NULL },
{ "GETMLHASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( GETMLHASH )}, NULL },
{ "INDIRECTRELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( INDIRECTRELATION )}, NULL },
{ "ISERIALCOMPOSITION", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISERIALCOMPOSITION )}, NULL },
{ "ISSQLWORKAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( ISSQLWORKAREA )}, NULL },
{ "ITEMCMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( ITEMCMP )}, NULL },
{ "KEYVALUEPAIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( KEYVALUEPAIR )}, NULL },
{ "LOGICALOPERATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( LOGICALOPERATOR )}, NULL },
{ "MSSQLEXPRESSIONTRANSLATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( MSSQLEXPRESSIONTRANSLATOR )}, NULL },
{ "MYSAFFECTEDROWS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSAFFECTEDROWS )}, NULL },
{ "MYSCLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSCLEAR )}, NULL },
{ "MYSCOLS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSCOLS )}, NULL },
{ "MYSCOMMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSCOMMIT )}, NULL },
{ "MYSCONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSCONNECT )}, NULL },
{ "MYSERRMSG", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSERRMSG )}, NULL },
{ "MYSEXEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSEXEC )}, NULL },
{ "MYSFETCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSFETCH )}, NULL },
{ "MYSFINISH", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSFINISH )}, NULL },
{ "MYSGETCONNID", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSGETCONNID )}, NULL },
{ "MYSKILLCONNID", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSKILLCONNID )}, NULL },
{ "MYSLINEPROCESSED", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSLINEPROCESSED )}, NULL },
{ "MYSQUERYATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSQUERYATTR )}, NULL },
{ "MYSRESSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSRESSTATUS )}, NULL },
{ "MYSRESULTSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSRESULTSTATUS )}, NULL },
{ "MYSROLLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSROLLBACK )}, NULL },
{ "MYSSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSSTATUS )}, NULL },
{ "MYSTABLEATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSTABLEATTR )}, NULL },
{ "MYSVERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( MYSVERS )}, NULL },
{ "NEWDBCLEARFILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( NEWDBCLEARFILTER )}, NULL },
{ "NEWDBCLEARRELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( NEWDBCLEARRELATION )}, NULL },
{ "NEWDBSETRELATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( NEWDBSETRELATION )}, NULL },
{ "NEWPARSEFORCLAUSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( NEWPARSEFORCLAUSE )}, NULL },
{ "OGETWORKAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( OGETWORKAREA )}, NULL },
{ "OPERATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( OPERATOR )}, NULL },
{ "PARAMETER", {HB_FS_PUBLIC}, {HB_FUNCNAME( PARAMETER )}, NULL },
{ "PARSERBASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( PARSERBASE )}, NULL },
{ "PGSAFFECTEDROWS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSAFFECTEDROWS )}, NULL },
{ "PGSCLEAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSCLEAR )}, NULL },
{ "PGSCOLS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSCOLS )}, NULL },
{ "PGSCOMMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSCOMMIT )}, NULL },
{ "PGSCONNECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSCONNECT )}, NULL },
{ "PGSERRMSG", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSERRMSG )}, NULL },
{ "PGSEXEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSEXEC )}, NULL },
{ "PGSFETCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSFETCH )}, NULL },
{ "PGSFINISH", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSFINISH )}, NULL },
{ "PGSGETDATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSGETDATA )}, NULL },
{ "PGSLINEPROCESSED", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSLINEPROCESSED )}, NULL },
{ "PGSQUERYATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSQUERYATTR )}, NULL },
{ "PGSRESSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSRESSTATUS )}, NULL },
{ "PGSRESULTSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSRESULTSTATUS )}, NULL },
{ "PGSROLLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSROLLBACK )}, NULL },
{ "PGSSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSSTATUS )}, NULL },
{ "PGSSTATUS2", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSSTATUS2 )}, NULL },
{ "PGSTABLEATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( PGSTABLEATTR )}, NULL },
{ "RELATIONBASE", {HB_FS_PUBLIC}, {HB_FUNCNAME( RELATIONBASE )}, NULL },
{ "RELATIONFACTORY", {HB_FS_PUBLIC}, {HB_FUNCNAME( RELATIONFACTORY )}, NULL },
{ "RELATIONMANAGER", {HB_FS_PUBLIC}, {HB_FUNCNAME( RELATIONMANAGER )}, NULL },
{ "REMOVEALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( REMOVEALL )}, NULL },
{ "SELECTFIRSTAREANOTINUSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SELECTFIRSTAREANOTINUSE )}, NULL },
{ "SERIALOPERATOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SERIALOPERATOR )}, NULL },
{ "SETFIREBIRDUSESHORTASNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETFIREBIRDUSESHORTASNUM )}, NULL },
{ "SETPGSOLDBEHAVIOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SETPGSOLDBEHAVIOR )}, NULL },
{ "SPLITCONDITION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SPLITCONDITION )}, NULL },
{ "SQLBINDBYVAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SQLBINDBYVAL )}, NULL },
{ "SQLEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SQLEX )}, NULL },
{ "SQLEX_GETFUNCTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SQLEX_GETFUNCTABLE )}, NULL },
{ "SQLFASTHASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( SQLFASTHASH )}, NULL },
{ "SQLRDD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SQLRDD )}, NULL },
{ "SQLRDD_GETFUNCTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SQLRDD_GETFUNCTABLE )}, NULL },
{ "SR_ADDCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ADDCONNECTION )}, NULL },
{ "SR_ADDRULENOTNULL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ADDRULENOTNULL )}, NULL },
{ "SR_ADDTOFILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ADDTOFILTER )}, NULL },
{ "SR_ADJUSTNUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ADJUSTNUM )}, NULL },
{ "SR_ALLINCACHE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ALLINCACHE )}, NULL },
{ "SR_ALLOCCO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ALLOCCO )}, NULL },
{ "SR_ALLOCEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ALLOCEN )}, NULL },
{ "SR_ALLOCST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ALLOCST )}, NULL },
{ "SR_ARRAYTOXML", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ARRAYTOXML )}, NULL },
{ "SR_AUTOCOMMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_AUTOCOMMIT )}, NULL },
{ "SR_BEGINTRANSACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_BEGINTRANSACTION )}, NULL },
{ "SR_BLANKVAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_BLANKVAR )}, NULL },
{ "SR_CDBVALUE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CDBVALUE )}, NULL },
{ "SR_CHANGESTRUCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CHANGESTRUCT )}, NULL },
{ "SR_CHECKCNN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CHECKCNN )}, NULL },
{ "SR_CHECKCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CHECKCONNECTION )}, NULL },
{ "SR_CHECKMGMNTIND", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CHECKMGMNTIND )}, NULL },
{ "SR_CLEANTABINFOCACHE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CLEANTABINFOCACHE )}, NULL },
{ "SR_CLEARFILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CLEARFILTER )}, NULL },
{ "SR_COLATTRIBUTE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_COLATTRIBUTE )}, NULL },
{ "SR_COMMIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_COMMIT )}, NULL },
{ "SR_COMMITTRANSACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_COMMITTRANSACTION )}, NULL },
{ "SR_CONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CONNECTION )}, NULL },
{ "SR_CREATECONSTRAINT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_CREATECONSTRAINT )}, NULL },
{ "SR_DBQUALIFY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DBQUALIFY )}, NULL },
{ "SR_DBREFRESH", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DBREFRESH )}, NULL },
{ "SR_DBSTRUCT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DBSTRUCT )}, NULL },
{ "SR_DELETEDNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DELETEDNAME )}, NULL },
{ "SR_DESCRIB", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DESCRIB )}, NULL },
{ "SR_DESERIALIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DESERIALIZE )}, NULL },
{ "SR_DESERIALIZE1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DESERIALIZE1 )}, NULL },
{ "SR_DETECTDBFROMDSN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DETECTDBFROMDSN )}, NULL },
{ "SR_DISABLEHISTORIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DISABLEHISTORIC )}, NULL },
{ "SR_DISCONN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DISCONN )}, NULL },
{ "SR_DRIVERC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DRIVERC )}, NULL },
{ "SR_DROPCONSTRAINT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DROPCONSTRAINT )}, NULL },
{ "SR_DROPINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DROPINDEX )}, NULL },
{ "SR_DROPRULENOTNULL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DROPRULENOTNULL )}, NULL },
{ "SR_DROPTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DROPTABLE )}, NULL },
{ "SR_DTODOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DTODOT )}, NULL },
{ "SR_DTOSDOT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DTOSDOT )}, NULL },
{ "SR_DTOUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_DTOUS )}, NULL },
{ "SR_ENABLEHISTORIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ENABLEHISTORIC )}, NULL },
{ "SR_END", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_END )}, NULL },
{ "SR_ENDCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ENDCONNECTION )}, NULL },
{ "SR_ENDTRANSACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ENDTRANSACTION )}, NULL },
{ "SR_ERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ERROR )}, NULL },
{ "SR_ERRORONGOTOTOINVALIDRECORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ERRORONGOTOTOINVALIDRECORD )}, NULL },
{ "SR_ESCAPENUM", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ESCAPENUM )}, NULL },
{ "SR_ESCAPESTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ESCAPESTRING )}, NULL },
{ "SR_EVALFILTERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_EVALFILTERS )}, NULL },
{ "SR_EXECDIR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_EXECDIR )}, NULL },
{ "SR_EXISTINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_EXISTINDEX )}, NULL },
{ "SR_EXISTTABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_EXISTTABLE )}, NULL },
{ "SR_FETCH", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FETCH )}, NULL },
{ "SR_FETCHSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FETCHSIZE )}, NULL },
{ "SR_FILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FILE )}, NULL },
{ "SR_FILTERSTATUS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FILTERSTATUS )}, NULL },
{ "SR_FIREBIRD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FIREBIRD )}, NULL },
{ "SR_FIXCACHEPOINTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FIXCACHEPOINTER )}, NULL },
{ "SR_FREECON", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FREECON )}, NULL },
{ "SR_FREEENV", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FREEENV )}, NULL },
{ "SR_FREESTM", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FREESTM )}, NULL },
{ "SR_FROMXML", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_FROMXML )}, NULL },
{ "SR_GETACTIVECONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETACTIVECONNECTION )}, NULL },
{ "SR_GETACTIVEDT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETACTIVEDT )}, NULL },
{ "SR_GETCNN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCNN )}, NULL },
{ "SR_GETCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTION )}, NULL },
{ "SR_GETCONNECTIONINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTIONINFO )}, NULL },
{ "SR_GETCONNECTOPTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCONNECTOPTION )}, NULL },
{ "SR_GETCURRINSTANCEID", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETCURRINSTANCEID )}, NULL },
{ "SR_GETERRMESSAGEMAX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETERRMESSAGEMAX )}, NULL },
{ "SR_GETFASTOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETFASTOPEN )}, NULL },
{ "SR_GETGLOBALOWNER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETGLOBALOWNER )}, NULL },
{ "SR_GETINDEXINFOBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETINDEXINFOBLOCK )}, NULL },
{ "SR_GETINFO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETINFO )}, NULL },
{ "SR_GETINTERNALID", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETINTERNALID )}, NULL },
{ "SR_GETNCONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETNCONNECTION )}, NULL },
{ "SR_GETNEXTRECORDBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETNEXTRECORDBLOCK )}, NULL },
{ "SR_GETORACLESYNTHETICVIRTUAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETORACLESYNTHETICVIRTUAL )}, NULL },
{ "SR_GETRDDNAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETRDDNAME )}, NULL },
{ "SR_GETSQL2008NEWTYPES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETSQL2008NEWTYPES )}, NULL },
{ "SR_GETSTACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETSTACK )}, NULL },
{ "SR_GETSVINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETSVINDEX )}, NULL },
{ "SR_GETSYNTHETICINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETSYNTHETICINDEX )}, NULL },
{ "SR_GETSYNTHETICINDEXMINIMUN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETSYNTHETICINDEXMINIMUN )}, NULL },
{ "SR_GETTABLEINFOBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETTABLEINFOBLOCK )}, NULL },
{ "SR_GETTOOLSOWNER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETTOOLSOWNER )}, NULL },
{ "SR_GETUNIQUESYSTEMID", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETUNIQUESYSTEMID )}, NULL },
{ "SR_GETUSEJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETUSEJSON )}, NULL },
{ "SR_GETUSEXMLFIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GETUSEXMLFIELD )}, NULL },
{ "SR_GOPHANTOM", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_GOPHANTOM )}, NULL },
{ "SR_HASFILTERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_HASFILTERS )}, NULL },
{ "SR_HASHISTORIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_HASHISTORIC )}, NULL },
{ "SR_HEXTOSTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_HEXTOSTR )}, NULL },
{ "SR_HISTEXPRESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_HISTEXPRESSION )}, NULL },
{ "SR_HISTEXPRESSIONWHERE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_HISTEXPRESSIONWHERE )}, NULL },
{ "SR_INDEXATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_INDEXATTR )}, NULL },
{ "SR_INIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_INIT )}, NULL },
{ "SR_ISWAHIST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ISWAHIST )}, NULL },
{ "SR_LASTSQLERROR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_LASTSQLERROR )}, NULL },
{ "SR_LISTCREATEDTABLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_LISTCREATEDTABLES )}, NULL },
{ "SR_LISTINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_LISTINDEX )}, NULL },
{ "SR_LISTLOCKS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_LISTLOCKS )}, NULL },
{ "SR_LISTTABLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_LISTTABLES )}, NULL },
{ "SR_LOGFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_LOGFILE )}, NULL },
{ "SR_MAXROWCACHE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_MAXROWCACHE )}, NULL },
{ "SR_MORERESULTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_MORERESULTS )}, NULL },
{ "SR_MSG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_MSG )}, NULL },
{ "SR_MSGLOGFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_MSGLOGFILE )}, NULL },
{ "SR_MYSQL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_MYSQL )}, NULL },
{ "SR_NUMRES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_NUMRES )}, NULL },
{ "SR_ODBC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ODBC )}, NULL },
{ "SR_ODBCGETLINES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ODBCGETLINES )}, NULL },
{ "SR_ODBCLINEPROCESSED", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ODBCLINEPROCESSED )}, NULL },
{ "SR_ODBCWRITEMEMO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ODBCWRITEMEMO )}, NULL },
{ "SR_ORDCONDSET", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ORDCONDSET )}, NULL },
{ "SR_PARSEFILENAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_PARSEFILENAME )}, NULL },
{ "SR_PARSERVERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_PARSERVERSION )}, NULL },
{ "SR_PCODEDESCR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_PCODEDESCR )}, NULL },
{ "SR_PGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_PGS )}, NULL },
{ "SR_PHFILE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_PHFILE )}, NULL },
{ "SR_QUICKAPPEND", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_QUICKAPPEND )}, NULL },
{ "SR_RECNONAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_RECNONAME )}, NULL },
{ "SR_RELEASELOCKS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_RELEASELOCKS )}, NULL },
{ "SR_RELOADFIELDMODIFIERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_RELOADFIELDMODIFIERS )}, NULL },
{ "SR_RELOADMLHASH", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_RELOADMLHASH )}, NULL },
{ "SR_RENAMETABLE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_RENAMETABLE )}, NULL },
{ "SR_RESETSTATISTICS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_RESETSTATISTICS )}, NULL },
{ "SR_ROLLBACK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ROLLBACK )}, NULL },
{ "SR_ROLLBACKTRANSACTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_ROLLBACKTRANSACTION )}, NULL },
{ "SR_RUNTIMEERR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_RUNTIMEERR )}, NULL },
{ "SR_SERIALIZE1", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SERIALIZE1 )}, NULL },
{ "SR_SETACTIVECONNECTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETACTIVECONNECTION )}, NULL },
{ "SR_SETACTIVEDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETACTIVEDATE )}, NULL },
{ "SR_SETACTIVEDT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETACTIVEDT )}, NULL },
{ "SR_SETALLOWRELATIONSININDX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETALLOWRELATIONSININDX )}, NULL },
{ "SR_SETALOCKWAIT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETALOCKWAIT )}, NULL },
{ "SR_SETAPPSITE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETAPPSITE )}, NULL },
{ "SR_SETAPPUSER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETAPPUSER )}, NULL },
{ "SR_SETBASELANG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETBASELANG )}, NULL },
{ "SR_SETBUFFERPOOLSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETBUFFERPOOLSIZE )}, NULL },
{ "SR_SETCOLLATION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETCOLLATION )}, NULL },
{ "SR_SETCOLPK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETCOLPK )}, NULL },
{ "SR_SETCONNECTATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETCONNECTATTR )}, NULL },
{ "SR_SETCONNECTIONLOGCHANGES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETCONNECTIONLOGCHANGES )}, NULL },
{ "SR_SETCONNECTOPTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETCONNECTOPTION )}, NULL },
{ "SR_SETCREATEASHISTORIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETCREATEASHISTORIC )}, NULL },
{ "SR_SETCURRDATE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETCURRDATE )}, NULL },
{ "SR_SETEXCLUSIVEMANAGEMENT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETEXCLUSIVEMANAGEMENT )}, NULL },
{ "SR_SETFASTOPEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETFASTOPEN )}, NULL },
{ "SR_SETFIELDDEFAULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETFIELDDEFAULT )}, NULL },
{ "SR_SETFILTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETFILTER )}, NULL },
{ "SR_SETFOUND", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETFOUND )}, NULL },
{ "SR_SETGLOBALOWNER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETGLOBALOWNER )}, NULL },
{ "SR_SETGOTOPONSCOPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETGOTOPONSCOPE )}, NULL },
{ "SR_SETHIDEHISTORIC", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETHIDEHISTORIC )}, NULL },
{ "SR_SETHIDERECNO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETHIDERECNO )}, NULL },
{ "SR_SETINDEXINFOBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETINDEXINFOBLOCK )}, NULL },
{ "SR_SETJOIN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETJOIN )}, NULL },
{ "SR_SETLGOTOPONFIRSTINTERACT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETLGOTOPONFIRSTINTERACT )}, NULL },
{ "SR_SETLOCKS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETLOCKS )}, NULL },
{ "SR_SETLUSEDBCATALOGS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETLUSEDBCATALOGS )}, NULL },
{ "SR_SETMININUMVARCHAR2SIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETMININUMVARCHAR2SIZE )}, NULL },
{ "SR_SETMULTILANG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETMULTILANG )}, NULL },
{ "SR_SETMYSQLMEMODATATYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETMYSQLMEMODATATYPE )}, NULL },
{ "SR_SETMYSQLNUMERICDATATYPE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETMYSQLNUMERICDATATYPE )}, NULL },
{ "SR_SETNEXTDT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETNEXTDT )}, NULL },
{ "SR_SETNEXTQUERY", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETNEXTQUERY )}, NULL },
{ "SR_SETNEXTRECORDBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETNEXTRECORDBLOCK )}, NULL },
{ "SR_SETNEXTSVVERS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETNEXTSVVERS )}, NULL },
{ "SR_SETNLINECOUNTRESULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETNLINECOUNTRESULT )}, NULL },
{ "SR_SETNWGCOMPAT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETNWGCOMPAT )}, NULL },
{ "SR_SETORACLESYNTHETICVIRTUAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETORACLESYNTHETICVIRTUAL )}, NULL },
{ "SR_SETPAGEREADSIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETPAGEREADSIZE )}, NULL },
{ "SR_SETRDDTEMP", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETRDDTEMP )}, NULL },
{ "SR_SETREVERSEINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETREVERSEINDEX )}, NULL },
{ "SR_SETROOTLANG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETROOTLANG )}, NULL },
{ "SR_SETSECONDLANG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSECONDLANG )}, NULL },
{ "SR_SETSERIALIZEARRAYASJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSERIALIZEARRAYASJSON )}, NULL },
{ "SR_SETSERIALIZEDSTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSERIALIZEDSTRING )}, NULL },
{ "SR_SETSHUTDOWN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSHUTDOWN )}, NULL },
{ "SR_SETSQL2008NEWTYPES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSQL2008NEWTYPES )}, NULL },
{ "SR_SETSTMTOPTION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSTMTOPTION )}, NULL },
{ "SR_SETSVINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSVINDEX )}, NULL },
{ "SR_SETSYNTHETICINDEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSYNTHETICINDEX )}, NULL },
{ "SR_SETSYNTHETICINDEXMINIMUN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETSYNTHETICINDEXMINIMUN )}, NULL },
{ "SR_SETTABLEINFOBLOCK", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTABLEINFOBLOCK )}, NULL },
{ "SR_SETTBLMGMNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTBLMGMNT )}, NULL },
{ "SR_SETTBLSPACEDATA", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTBLSPACEDATA )}, NULL },
{ "SR_SETTBLSPACEINDX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTBLSPACEINDX )}, NULL },
{ "SR_SETTBLSPACELOB", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTBLSPACELOB )}, NULL },
{ "SR_SETTIMETRACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTIMETRACE )}, NULL },
{ "SR_SETTOOLSOWNER", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTOOLSOWNER )}, NULL },
{ "SR_SETTRACELOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETTRACELOG )}, NULL },
{ "SR_SETUSEDTHISTAUTO", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETUSEDTHISTAUTO )}, NULL },
{ "SR_SETUSEJSON", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETUSEJSON )}, NULL },
{ "SR_SETUSESEQUENCES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETUSESEQUENCES )}, NULL },
{ "SR_SETUSEXMLFIELD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SETUSEXMLFIELD )}, NULL },
{ "SR_SHOWVECTOR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SHOWVECTOR )}, NULL },
{ "SR_SQLCODEGEN", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SQLCODEGEN )}, NULL },
{ "SR_SQLPARSE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SQLPARSE )}, NULL },
{ "SR_SQLQUOTEDSTRING", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_SQLQUOTEDSTRING )}, NULL },
{ "SR_STARTLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_STARTLOG )}, NULL },
{ "SR_STARTTRACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_STARTTRACE )}, NULL },
{ "SR_STOPLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_STOPLOG )}, NULL },
{ "SR_STOPTRACE", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_STOPTRACE )}, NULL },
{ "SR_STRTOHEX", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_STRTOHEX )}, NULL },
{ "SR_TABLEATTR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_TABLEATTR )}, NULL },
{ "SR_TABLES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_TABLES )}, NULL },
{ "SR_TBLMGMNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_TBLMGMNT )}, NULL },
{ "SR_TCNEXTRECORD", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_TCNEXTRECORD )}, NULL },
{ "SR_TRANSACTIONCOUNT", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_TRANSACTIONCOUNT )}, NULL },
{ "SR_UCHARTOVAL", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_UCHARTOVAL )}, NULL },
{ "SR_USEDELETEDS", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_USEDELETEDS )}, NULL },
{ "SR_USENULLSFIRST", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_USENULLSFIRST )}, NULL },
{ "SR_USESEQUENCES", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_USESEQUENCES )}, NULL },
{ "SR_VAL2CHAR", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_VAL2CHAR )}, NULL },
{ "SR_VAL2CHARQ", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_VAL2CHARQ )}, NULL },
{ "SR_VERSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_VERSION )}, NULL },
{ "SR_WORKAREA", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_WORKAREA )}, NULL },
{ "SR_WORKAREAFILENAME", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_WORKAREAFILENAME )}, NULL },
{ "SR_WRITEDBLOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_WRITEDBLOG )}, NULL },
{ "SR_WRITETIMELOG", {HB_FS_PUBLIC}, {HB_FUNCNAME( SR_WRITETIMELOG )}, NULL },
{ "TODICTIONARY", {HB_FS_PUBLIC}, {HB_FUNCNAME( TODICTIONARY )}, NULL },
{ "TRANSLATIONRESULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( TRANSLATIONRESULT )}, NULL },
{ "VALUEEXPRESSION", {HB_FS_PUBLIC}, {HB_FUNCNAME( VALUEEXPRESSION )}, NULL },
{ "VISUALIZE", {HB_FS_PUBLIC}, {HB_FUNCNAME( VISUALIZE )}, NULL },
{ "XFIRST", {HB_FS_PUBLIC}, {HB_FUNCNAME( XFIRST )}, NULL },
{ "XFIRSTORDEFAULT", {HB_FS_PUBLIC}, {HB_FUNCNAME( XFIRSTORDEFAULT )}, NULL },
{ "XSELECT", {HB_FS_PUBLIC}, {HB_FUNCNAME( XSELECT )}, NULL },
{ "XSELECTMANY", {HB_FS_PUBLIC}, {HB_FUNCNAME( XSELECTMANY )}, NULL },
{ "_SR_REGISTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( _SR_REGISTER )}, NULL },
{ "_SR_SCANEXEC", {HB_FS_PUBLIC}, {HB_FUNCNAME( _SR_SCANEXEC )}, NULL },
{ "_SR_SCANEXECALL", {HB_FS_PUBLIC}, {HB_FUNCNAME( _SR_SCANEXECALL )}, NULL },
{ "_SR_UNREGISTER", {HB_FS_PUBLIC}, {HB_FUNCNAME( _SR_UNREGISTER )}, NULL },
{ "__SR_STARTSQL", {HB_FS_PUBLIC}, {HB_FUNCNAME( __SR_STARTSQL )}, NULL },
{ "__HBEXTERN__SQLRDD__", {HB_FS_PUBLIC | HB_FS_FIRST | HB_FS_LOCAL}, {HB_FUNCNAME( __HBEXTERN__SQLRDD__ )}, NULL }
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_SQLRDD, "source/sqlrdd.hbx", 0x0, 0x0003 )

#if defined( HB_PRAGMA_STARTUP )
   #pragma startup hb_vm_SymbolInit_SQLRDD
#elif defined( HB_DATASEG_STARTUP )
   #define HB_DATASEG_BODY    HB_DATASEG_FUNC( hb_vm_SymbolInit_SQLRDD )
   #include "hbiniseg.h"
#endif

HB_FUNC( __HBEXTERN__SQLRDD__ )
{
	static const HB_BYTE pcode[] =
	{
		7
	};

	hb_vmExecute( pcode, symbols );
}

